version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:ap-south-1:997753278599:task-definition/Techserverglobal-TaskDefinition:2"
       LoadBalancerInfo:
         ContainerName: "angular"
         ContainerPort: 80
