version: 0.2 

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - ECR_LOGIN=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo $ECR_LOGIN | docker login -u AWS --password-stdin 997753278599.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=997753278599.dkr.ecr.ap-south-1.amazonaws.com/reactrepository
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $REPOSITORY_URI
  # Generate image definition for ECS
      - printf '[{"name":"angular-app","imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

